import json
import re
from pathlib import Path
from typing import Dict, List, Any
from jinja2 import Template

def get_step_name(action: str, fingerprint: dict) -> str:
    """Generate a clean, deterministic, valid Python identifier name for a step."""
    attributes = fingerprint.get("attributes") or {}
    tag = fingerprint.get("tag") or "element"
    
    # Try id first
    for attr in ["data-testid", "data-test", "data-qa", "id", "name"]:
        val = attributes.get(attr)
        if val and isinstance(val, str):
            clean = re.sub(r"[^a-zA-Z0-9_]", "_", val).strip("_")
            if clean:
                return f"{action}_{clean.lower()}"
                
    # Try classes
    classes_str = attributes.get("class") or ""
    if classes_str:
        classes = classes_str.split() if isinstance(classes_str, str) else list(classes_str)
        clean_classes = [re.sub(r"[^a-zA-Z0-9_]", "_", c).strip("_") for c in classes]
        clean_classes = [c for c in clean_classes if c]
        if clean_classes:
            return f"{action}_{clean_classes[0].lower()}"
            
    # Try text content
    text = fingerprint.get("text") or ""
    if text and len(text) < 20:
        clean = re.sub(r"[^a-zA-Z0-9_]", "_", text).strip("_")
        if clean:
            return f"{action}_{clean.lower()}"
            
    return f"{action}_{tag.lower()}"

class TestGenerator:
    """
    Generates runnable standalone pytest/playwright scripts from captured interaction flows.
    """
    __test__ = False

    def __init__(self, flow_path: str):
        self.flow_path = Path(flow_path)
        with open(self.flow_path, "r", encoding="utf-8") as f:
            self.flow_data = json.load(f)

    def generate(self) -> Dict[str, Any]:
        """Convert recorded flow steps into a structured test definition."""
        steps = []
        url = self.flow_data.get("url", "")
        
        # Add initial navigate step
        steps.append({
            "name": "navigate_to_start",
            "action": "navigate",
            "value": url,
            "selectors": [],
            "assertions": [{"kind": "url", "value": url}]
        })
        
        for idx, step in enumerate(self.flow_data.get("steps", [])):
            fingerprint = step.get("fingerprint") or {}
            action = step.get("action")
            value = step.get("value")
            
            step_name = f"{get_step_name(action, fingerprint)}_{idx}"
            
            # Map assertions to steps
            assertions = []
            for a in step.get("assertions", []):
                assertions.append({
                    "kind": a.get("kind"),
                    "value": a.get("value")
                })
                
            steps.append({
                "name": step_name,
                "action": action,
                "value": value,
                "selectors": fingerprint.get("selectors", []),
                "assertions": assertions
            })
            
        return {
            "url": url,
            "steps": steps
        }

    def export_pytest(self, output_path: str) -> str:
        """Render a standalone, self-contained pytest file from the flow definition."""
        test_def = self.generate()
        
        # Jinja2 template
        template_str = """# Generated by ScrapeWizard Test Generator
import pytest
from playwright.sync_api import sync_playwright

STEPS = {{ steps_json }}

@pytest.fixture(scope="function")
def page():
    \"\"\"Self-contained Playwright page fixture to ensure zero setup overhead.\"\"\"
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page_obj = context.new_page()
        yield page_obj
        context.close()
        browser.close()

def resolve(page, selectors):
    \"\"\"Try each selector strategy in rank order.\"\"\"
    for s in selectors:
        try:
            if s["kind"] == "css":
                loc = page.locator(s["value"])
            else:
                loc = page.locator(f"xpath={s['value']}")
            if loc.count() > 0:
                # Wait for element to be attached
                loc.first.wait_for(state="attached", timeout=2000)
                return loc.first
        except Exception:
            continue
    raise Exception(f"Failed to resolve element using selector ladder: {selectors}")

def test_flow(page):
    # Set standard viewport
    page.set_viewport_size({"width": 1280, "height": 720})
    
    for step in STEPS:
        action = step["action"]
        val = step["value"]
        selectors = step["selectors"]
        
        print(f"Running step: {step['name']} ({action})")
        
        if action == "navigate":
            page.goto(val)
        elif action == "click":
            el = resolve(page, selectors)
            el.click()
        elif action == "fill":
            el = resolve(page, selectors)
            el.fill(val)
            
        # Run assertions
        for assertion in step.get("assertions", []):
            kind = assertion["kind"]
            expected = assertion["value"]
            if kind == "url":
                # Wait up to 3 seconds for page URL to match
                try:
                    page.wait_for_url(expected, timeout=3000)
                except Exception:
                    pass
                assert page.url.rstrip("/") == expected.rstrip("/"), f"Expected URL: {expected}, got: {page.url}"
            elif kind == "visible":
                # If we have selectors in the step, use them, otherwise use the assertion value as CSS
                target_selectors = selectors if selectors else [{"kind": "css", "value": expected}]
                el = resolve(page, target_selectors)
                assert el.is_visible(), f"Element {expected} is not visible"
"""
        template = Template(template_str)
        # Format steps as json representation
        steps_json = json.dumps(test_def["steps"], indent=4)
        
        # Render
        rendered = template.render(steps_json=steps_json)
        
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(rendered)
            
        return rendered
